theme: jekyll-theme-dinky 
encoding: utf-8
exclude: ['jekyll_notes.txt', 'assetsprivate']
google_analytics: UA-114934911-1
repository: paphillips/DFBBlog
title: DFB Topics
description: Cypress PSoC Digital Filter Block (DFB) Topics
logo: favicon.png
paginate: 12
theme: jekyll-theme-dinky
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
plugins:
  - jekyll-sitemap